Rails:
  Enabled: true

AllCops:
  Exclude:
    - bin/*
    - Rakefile
    - Gemfile
    - config/**/*
    - notepad/**/*
    - spec/**/*
    - test/**/*
    - db/**/*
    - deploy/*.rb
    - deploy.rb
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

TrailingCommaInLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

Documentation:
  Enabled: false

StringLiterals:
  Enabled: false

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false